# Generated by Django 3.2.9 on 2021-11-29 14:37

from django.db import migrations, models
import django.utils.timezone
import listing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('offer_type', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('pool', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('photo_main', models.ImageField(upload_to=listing.models.change_image_name)),
                ('photo_1', models.ImageField(blank=True, upload_to=listing.models.change_image_name)),
                ('photo_2', models.ImageField(blank=True, upload_to=listing.models.change_image_name)),
                ('photo_3', models.ImageField(blank=True, upload_to=listing.models.change_image_name)),
                ('photo_4', models.ImageField(blank=True, upload_to=listing.models.change_image_name)),
                ('photo_5', models.ImageField(blank=True, upload_to=listing.models.change_image_name)),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
