# Generated by Django 3.2.9 on 2021-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='offer_type',
            field=models.CharField(choices=[('', 'Offer Type'), ('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100),
        ),
    ]
