# Generated by Django 3.2.9 on 2021-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor',
            field=models.CharField(default='wgrace@robertbushrestate.com', max_length=256),
            preserve_default=False,
        ),
    ]
